<?php

// Edit this file to your langugage

$lang = array(
  "warning"                               => "Attenzione!",
  "login"                                 => "Login",
  "register"                              => "Registrati",
  "please_sign_in"                        => "Per Favore Accedi",  
  "password"                              => "Password",
  "password_repeat"                       => "Password (ripeti)",
  "remember_me"                           => "Ricorda",
  "sign_in"                               => "Accedi",
  "create_member"                         => "Crea un membro",
  "you_were_logged_out"                   => "Sei stato disconnesso!",
  
  "sounds"                                => "Suoni",
  "visible"                               => "Visibile",
  "profile"                               => "Profilo",
  "change_password"                       => "Cambia password",
  "administration"                        => "Amministrazione",
  "settings"                              => "Impostazioni",
  "users"                                 => "Utenti",
  "add_user"                              => "Aggiungi Utente",
  "manage"                                => "Gestisci",
  "rooms"                                 => "Stanze",
  "add_room"                              => "Aggiungi Stanze",
  "logout"                                => "Disconnetti",
  "page"                                  => "Pagina",
  
  "online_users"                          => "Utenti Online",
  "response"                              => "Scrivi messaggio...",
  "send"                                  => "Invia",
  "upload_file"                           => "Carica file",
  "loading_older"                         => "Carica più vecchi ...",
  "start_chat_with"                       => "Messaggia con ...",
  "online"                                => "Online",
  "change_avatar"                         => "Cambia avatar",
  "delete_avatar"                         => "Elimina avatar",
  "ban"                                   => "Banna",
  "informations"                          => "Informazioni",
  "edit"                                  => "Modifica",
  "discard"                               => "Annulla",
  "save_changes"                          => "Salva modifiche",
  "now_using_password"                    => "Ora usando password",
  "new_password"                          => "Nuova password",
  "repeat_new_password"                   => "Ripeti la nuova password",
  "settings"                              => "Impostazioni",
  "save_settings"                         => "Salva impostazioni",
  "banned"                                => "Bannato",
  "last_login"                            => "Ultimo login",
  "registered"                            => "Registrato",
  
  "check_empty_fields"                    => "Verifica i campi vuoti!",
  "this_account_has_ban"                  => "Questo utente è bannato!",
  "check_login_and_password"              => "Verifica login e password!",
  "login_contain"                         => "Login can contain characters a-z and numbers 0-9, length must be 3-15!",
  "passwords_not_match"                   => "Le password non corrispondono!",
  "login_is_already_using"                => "Login is already using!",
  "internal_error"                        => "Errore interno!",
  "not_permitted"                         => "Non permesso!",
  "incorrect_old_password"                => "Password vecchia non corretta!",
  "password_successfully_changed"         => "Password sostituita!",
  
  "write_text"                            => "Scrivi un messaggio!",
  "too_long_message"                      => "Messaggio troppo lungo!",
  "uploading"                             => "Caricando...",
  
  "site_name"                             => "Nome del sito",
  "profile_items"                         => "Profilo",
  "profile_items_warning"                 => "Inserisci così 'key':'valore', 'key':'valore1' ...",
  "refresh_delay"                         => "Aggiorna delay",
  "refresh_delay_info"                    => "Delay per prelevare nuove info",
  "milisecond"                            => "ms",
  "delay_for_offline"                     => "Delay per offline",
  "second"                                => "sec",
  "delay_for_offline_info"                => "Delay in which user must send refresh request",
  "attachment_max_size"                   => "max.size degli allegati",
  "megabyte"                              => "MB",
  "enabled_private_messages"              => "Abilita i messaggi privati",
  "enabled_registration"                  => "Abilita registrazioni utente",
  "enabled_registration_info"             => "Se le registrazioni sono disabilitate, solo gli admin possono aggiungere utenti",
  "max_characters_in_message"             => "Max numero di caratteri per messaggio",
  "messages_per_page"                     => "Numero di messaggi per pagina",
  "datetime_format"                       => "Formato Datetime",
  "datetime_format_info"                  => "Controlla <a href='http://php.net/manual/en/function.date.php#refsect1-function.date-parameters' target='_blank'>la funzione PHP date()</a>",
  "available_attachments_for_members_at"  => "Allegati disponibili per i membri su:",
  "private_messages"                      => "Messaggi privati",
  "administrator"                         => "Amministratore",
  "member"                                => "Utente Semplice",
  "settings_bottom_info"                  => "[ Un refresh di pagina è necessario per aggiornare le impostazioni ]",
  "level"                                 => "Livello",
  "user_successfully_added"               => "User successfully added",
  "user_successfully_updated"             => "User successfully updated",
  "unknown_level"                         => "Livello sconosciuto",
  "yes"                                   => "Si",
  "no"                                    => "No",
  "manage_users"                          => "Gestisci utenti",
  "id"                                    => "ID",
  "actions"                               => "Azioni",
  "delete"                                => "Elimina",
  "are_you_sure"                          => "Sei sicuro?",
  "edit_user"                             => "Modifica Utente",
  
  "select_name_for_new_room"              => "Scegli il nome per la nuova stanza:",
  "name"                                  => "Nome",
  "select_new_name"                       => "Scegli il nuovo nome",
  "manage_rooms"                          => "Gestisci stanze",
  
  //added in 2.1
  "direction_rtl"                         => "Direzione right-to-left",
  "next_message_delay"                    => "Delay in tempo per inviare il prossimo messaggio",
  "you_are_too_fast"                     => "Sei troppo veloce!"
);